version: "2"
services:
  mysql:
    image: mysql:8
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password --port=3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dsc-node
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      USER: 1000

  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  api:
    image: node:14.16
    hostname: api
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    ports:
      - "3002:3002"
      - "9229:9229"
    volumes:
      - ../:/usr/src/service
    working_dir: /usr/src/service/api
    command: "npm start"
